name: hid-examples
version: 0.5
synopsis: Examples to accompany the book "Haskell in Depth"
description:
        This package provides source code examples which accompany the book
        "Haskell in Depth" by Vitaly Bragilevsky (Manning Publications 2020).
        You may want to get this package via @cabal get hid-examples@
        and explore its content.

category:            Sample Code
license:             BSD3
author: Vitaly Bragilevsky
maintainer: Vitaly Bragilevsky <vit.bragilevsky@gmail.com>
github: bravit/hid-examples
extra-source-files:
    - ChangeLog.md
    - LICENSE
    - README.md
    - stack.yaml
    - .travis.yml
    - appveyor.yml
    - package.yaml

data-files:
    - data/*.*
    - data/texts/*.*
    - data/tests/iplookup/*.*
    - data/benchmarks/iplookup/*.*

tested-with: GHC == 8.6.5, GHC == 8.8.3

dependencies: base >=4.12 && <4.15

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Widentities
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wno-unused-top-binds
  - -Wno-orphans
executables:
    # Preface
    hello:
        main: intro/hello.hs
    # Chapter 1
    vocab1:
        source-dirs: ch01
        main: vocab1.hs
        other-modules: []
        dependencies: text >=1.2 && <1.3
    vocab2:
        source-dirs: ch01
        main: vocab2.hs
        other-modules: []
        dependencies: text >=1.2 && <1.3
    vocab3:
        source-dirs: ch01
        main: vocab3.hs
        other-modules: []
        other-extensions:
          - OverloadedStrings
        dependencies:
          - text >=1.2 && <1.3
          - fmt >=0.5 && <0.7
    # Chapter 2
    # 2.1
    radar:
        source-dirs: ch02/radar
        main: Main.hs
        other-modules: Radar
        other-extensions:
          - DeriveAnyClass
        dependencies:
          - fmt >=0.5 && <0.7
    # 2.2
    person-derived:
        source-dirs: ch02/person
        main: derived-show.hs
        other-modules: Person
    person-implemented:
        source-dirs: ch02/person
        main: implemented-show.hs
        other-modules: Person
    person-text:
        source-dirs: ch02/person
        main: text-show.hs
        other-modules: Person
        dependencies:
          - text-show >=3.0 && <4
    # Chapter 3
    stockquotes:
        source-dirs: stockquotes
        main: Main.hs
        other-extensions:
          - RecordWildCards
          - OverloadedStrings
          - DeriveGeneric
          - DeriveAnyClass
        dependencies:
          - bytestring >=0.10 && <0.11
          - blaze-html >=0.9 && <0.10
          - optparse-applicative >=0.14 && <0.16
          - time >=1.8 && <1.11
          - text >=1.2 && <1.3
          - fmt >=0.5 && <0.7
          - Chart >=1.8 && <1.10
          - Chart-diagrams >=1.8 && <1.10
          - cassava >=0.5 && <0.6
          - colonnade >= 1.1 && < 1.3
          - blaze-colonnade >= 1.1 && < 1.3
    # Chapter 5
    maybe:
        source-dirs: ch05
        main: maybe.hs
    reader:
        source-dirs: ch05
        main: reader.hs
        other-extensions:
          - NamedFieldPuns
        dependencies:
          - mtl >=2.0 && <2.3
    genSQL:
        source-dirs: ch05
        main: genSQL.hs
        other-extensions:
          - OverloadedStrings
          - ViewPatterns
        dependencies:
          - text >=1.2 && <1.3
          - mtl >=2.0 && <2.3
    gcd:
        source-dirs: ch05
        main: gcd.hs
        dependencies:
          - mtl >=2.0 && <2.3
    sumlist:
        source-dirs: ch05
        main: sumlist.hs
        dependencies:
          - mtl >=2.0 && <2.3
    weapons:
        source-dirs: ch05
        main: weapons.hs
        dependencies:
          - mtl >=2.0 && <2.3
          - random >=1.0 && <1.2
    prefix-postfix:
        source-dirs: expr
        main: prefix-postfix.hs
        other-modules: [Expr, ShuntingYard]
        dependencies:
        - text-show >=3.0 && <4
        - mtl >=2.0 && <2.3
    dicegame:
        source-dirs: ch05
        main: dicegame.hs
        dependencies:
          - mtl >=2.0 && <2.3
          - random >=1.0 && <1.2
    ioref:
        source-dirs: ch05
        main: ioref.hs
    filecount:
        source-dirs: ch05
        main: filecount.hs
        dependencies:
          - extra >=1.5 && <1.8
    stref:
        source-dirs: ch05
        main: stref.hs
    countzeros:
        source-dirs: ch05
        main: countzeros.hs
    # Chapter 6
    evalrpn1:
        source-dirs: expr/rpn
        main: evalrpn1.hs
        other-modules: [EvalRPN]
        dependencies:
          - mtl >= 2.0 && < 2.3
    evalrpn2:
        source-dirs: expr/rpn
        main: evalrpn2.hs
        other-modules: [EvalRPNTrans]
        dependencies:
          - mtl >= 2.0 && < 2.3
    evalrpn3:
        source-dirs: expr/rpn
        main: evalrpn3.hs
        other-modules: [MyMaybeT, EvalRPNTrans2]
        dependencies:
          - mtl >= 2.0 && < 2.3
          - transformers >= 0.5 && < 0.6
        other-extensions:
          - FlexibleInstances
          - MultiParamTypeClasses
          - UndecidableInstances
          - InstanceSigs
          - LambdaCase
    du:
        source-dirs: du
        main: Main.hs
        dependencies:
          - mtl >=2.0 && <2.3
          - filepath >= 1.4.1 && < 1.5
          - directory >= 1.3 && < 1.4
          - unix-compat >= 0.5 && < 0.6
          - optparse-applicative >= 0.14 && < 0.16
          - text >=1.2 && <1.3
          - text-show >=3.0 && <4
          - extra >=1.5 && <1.8
        default-extensions:
          - RecordWildCards
          - NamedFieldPuns
          - OverloadedStrings
        other-extensions:
          - GeneralizedNewtypeDeriving
    # Chapter 7
    rpnexpr:
        source-dirs: expr/rpn
        main: rpnexpr.hs
        other-modules:
          - EvalRPNExcept
        other-extensions:
          - OverloadedStrings
        dependencies:
          - mtl >= 2.0 && < 2.3
          - transformers >= 0.5 && < 0.6
          - text >=1.2 && <1.3
          - text-show >=3.0 && <4
    div:
      source-dirs: ch07
      main: div.hs
      dependencies:
        - exceptions >= 0.10 && < 0.11
    suntimes:
        source-dirs: suntimes
        main: Main.hs
        dependencies:
          - mtl >= 2.0 && < 2.3
          - transformers >= 0.5 && < 0.6
          - time >=1.8 && <1.11
          - text >=1.2 && <1.3
          - exceptions >= 0.10 && < 0.11
          - aeson >= 1.2 && < 1.5
          - req >= 2.0 && < 3.2
          - http-client >= 0.4 && < 0.7
          - optparse-applicative >= 0.14 && < 0.16
          - bytestring >= 0.10 && < 0.11
        default-extensions:
          - OverloadedStrings
        other-extensions:
          - RecordWildCards
          - DeriveGeneric
    logging:
      source-dirs: ch07
      main: logging.hs
      dependencies:
        - monad-logger >= 0.3 && < 0.4
        - mtl >= 2.0 && < 2.3
        - transformers >= 0.5 && < 0.6
        - text >=1.2 && <1.3
    # Chapter 8
    iplookup:
        main: ip/iplookup/Main.hs
        dependencies:
          - exceptions >= 0.10 && < 0.11
          - optparse-applicative >= 0.14 && < 0.16
          - iplookup-lib
    ipgen:
        main: ip/ipgen/Main.hs
        dependencies:
          - ipgen-lib
          - exceptions >= 0.10 && < 0.11
          - optparse-applicative >= 0.14 && < 0.16
          - hedgehog >= 0.5 && < 1.1
    # Chapter 10
    iplookup-simulation:
        main: ip/iplookup-simulation.hs
        dependencies:
          - random >=1.0 && <1.2
          - iplookup-lib
    # Chapter 11
    # 11.1
    weights-phantom:
        main: ch11/weights-phantom/Main.hs
        other-extensions:
          - GeneralizedNewtypeDeriving
    describe-proxies:
        main: ch11/describe-proxies/Main.hs
        other-extensions:
          - PolyKinds
          - InstanceSigs
    describe-type-apps:
        main: ch11/describe-type-apps/Main.hs
        other-extensions:
          - PolyKinds
          - AllowAmbiguousTypes
          - TypeApplications
    type-operators:
        main: ch11/type-operators/Main.hs
        other-extensions:
          - TypeOperators
          - NoStarIsType
    weights-kinds:
        main: ch11/weights-kinds/Main.hs
        other-extensions:
          - DataKinds
          - KindSignatures
          - GeneralizedNewtypeDeriving
    type-lits:
        main: ch11/type-lits/Main.hs
        other-extensions:
          - DataKinds
          - KindSignatures
          - ScopedTypeVariables
    type-families:
        main: ch11/type-families/Main.hs
        other-extensions:
          - TypeFamilies
          - FlexibleInstances
    dynvalues-gadt:
        main: ch11/dynvalues-gadt/Main.hs
        other-extensions:
          - GADTs
    # 11.2
    api-stage0:
        main: ch11/api/Api0.hs
    api-stage1:
        main: ch11/api/Api1.hs
    api-stage2:
        main: ch11/api/Api2.hs
        other-extensions:
          - KindSignatures
          - TypeOperators
          - PolyKinds
          - DataKinds
          - TypeFamilies
    api-stage3:
        main: ch11/api/Api3.hs
        other-extensions:
          - KindSignatures
          - TypeOperators
          - PolyKinds
          - DataKinds
          - TypeFamilies
          - FlexibleInstances
          - InstanceSigs
          - ScopedTypeVariables
    # 11.3
    expr-gadt:
        main: ch11/expr-gadt/Main.hs
        other-extensions:
          - GADTSyntax
          - GADTs
    doors-type-equality:
        main: ch11/doors/TypeEq.hs
        other-extensions:
          - DataKinds
          - GADTs
          - KindSignatures
          - ExplicitForAll
          - TypeOperators
          - StandaloneDeriving
    doors-singletons:
        main: ch11/doors/Sing.hs
        other-extensions:
          - DataKinds
          - GADTs
          - TypeOperators
          - KindSignatures
          - StandaloneDeriving
    # 11.4
    nummod-rank-n:
        source-dirs: ch11/nummod-rank-n/
        main: Main.hs
        other-extensions:
          - RankNTypes
    xlist-data-families:
        source-dirs: ch11/data-families/
        main: Main.hs
        other-extensions:
          - TypeFamilies
    graph-assoc-tf:
        source-dirs: ch11/graph-assoc-tf/
        main: Main.hs
        dependencies:
          - containers >= 0.5 && < 0.7
        other-extensions:
          - TypeFamilies
          - FlexibleContexts

internal-libraries:
    # Chapter 2
    radar-lib:
        source-dirs: ch02/radar
        exposed-modules: Radar
        other-modules: []
    expr-simple:
        source-dirs: expr
        exposed-modules: Expr
        other-modules: []
        dependencies:
          - text-show >=3.0 && <4
    contexts:
        source-dirs: ch02
        exposed-modules: Contexts
        other-modules: []
        dependencies:
          - mtl >=2.0 && <2.3
    # Chapter 5
    shunting-yard:
        source-dirs: expr
        exposed-modules: ShuntingYard, Expr
        other-modules: []
        dependencies:
          - expr-simple
          - mtl >=2.0 && <2.3
          - text-show >=3.0 && <4
    # Chapter 8
    iplookup-lib:
        source-dirs: ip/iplookup
        exposed-modules:
          - IPTypes
          - LookupIP
          - ParseIP
          - FastLookup
        other-modules: []
        dependencies:
          - split >= 0.2 && < 0.3
          - fingertree >= 0.1 && < 0.2
        other-extensions:
          - TypeApplications
        ghc-options:
          - -Wno-incomplete-uni-patterns
    ipgen-lib:
        source-dirs: ip/ipgen
        exposed-modules:
          - GenIP
        other-modules: []
        dependencies:
          - iplookup-lib
          - hedgehog >= 0.5 && < 1.1

tests:
    # Chapter 2
    radar-test:
        source-dirs: tests/radar
        main: Test.hs
        other-modules: []
        dependencies:
          - radar-lib
          - random >=1.0 && <1.2
    expr-simple-test:
        source-dirs: tests/expr
        main: Test1.hs
        other-modules: []
        dependencies:
          - expr-simple
          - hint >=0.7 && <0.10
          - text-show >=3.0 && <4
    # Chapter 5
    shunting-yard-test:
        source-dirs: tests/expr
        main: Test2.hs
        other-modules: []
        dependencies:
          - shunting-yard
          - text-show >=3.0 && <4
          - text >=1.2 && <1.3
    # Chapter 8
    iplookup-test:
        main: Test.hs
        source-dirs: tests/iplookup
        dependencies:
          - iplookup-lib
          - ipgen-lib
          - tasty >= 0.11 && < 1.4
          - tasty-hspec >= 1.1 && < 1.2
          - tasty-hedgehog >= 0.1 && < 1.1
          - hedgehog >= 0.5 && < 1.1
          - tasty-golden >= 2.3 && < 2.4
          - filepath >= 1.4.1 && < 1.5
        ghc-options:
          - -Wno-type-defaults
    iplookup-doctest:
        main: tests/iplookup-doctest/Doctests.hs
        ghc-options:
          - -threaded
        dependencies:
          - doctest >= 0.12 && < 0.17

benchmarks:
    # Chapter 10
    primcheck:
        main: Bench.hs
        source-dirs: benchmarks/primcheck
        dependencies:
          - criterion >= 1.4 && < 1.6
    iplookup-bench:
        main: Bench.hs
        generated-other-modules: Paths_hid_examples
        source-dirs: benchmarks/iplookup
        dependencies:
          - iplookup-lib
          - criterion >= 1.4 && < 1.6
          - deepseq >= 1.3 && <1.5
